runtime: python3
api_version: 1
threadsafe: true

handlers:
- url: /
  script: friendsZones.app

- url: /index\.html
  script: friendsZones.app

- url: /stylesheets
  static_dir: stylesheets

- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: not_found.app