runtime: python3
api_version: 1
threadsafe: true

handlers:
- url: /
  script: friendsZones.app

- url: /sing_in/
  script: friendsZones.app

- url: /favorites/
  script: friendsZones.app

- url: /all_favorites/
  script: friendsZones.app

- url: /update_user/
  script: friendsZones.app

- url: /block/
  script: friendsZones.app

- url: /push/
  script: friendsZones.app

- url: /inradius/
  script: friendsZones.app

- url: /upload/
  script: friendsZones.app
  
- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: not_found.app