# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsZones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='radius',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
