# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsZones', '0002_auto_20180112_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deviceToken',
            new_name='AuthenticationToken',
        ),
    ]
