# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsZones', '0003_auto_20180112_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='userID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
