# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsZones', '0005_auto_20180117_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DeviceType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
